name: ez_image_fetch_example
version: 0.0.1
description: An example app showing how to use the ez_image_fetch_package.
publish_to: "none" # Prevents publishing the example to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ez_image_fetch_package:
    path: ../
  native_dio_adapter: ^1.3.0
  path_provider: ^2.1.4
  logger: ^2.4.0
  crypto: ^3.0.5
  dio: ^5.6.0
  # Points to the main package
  
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
      - assets/dog.png
